"""add foreign key to Review

Revision ID: 554caaa63e40
Revises: 1eb0ea679a04
Create Date: 2024-07-26 21:12:01.493514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554caaa63e40'
down_revision = '1eb0ea679a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
